// generateReadme function populating the README.md
function generateMarkdown(content) {
    return `
<h1 align="center">${content.title}</h1>
  
![badge](https://img.shields.io/badge/license-${content.license}-lightblue)<br />

## Description
${content.description}

## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [Tests](#tests)
- [Contributing](#contributing)
- [License](#license)
- [Questions](#questions)

## Installation
${content.installation}

## Usage
${content.usage}

## Tests
${content.tests}

## Contributing
${content.contribution}

## License
![badge](https://img.shields.io/badge/license-${content.license}-lightblue)
<br />
The README.md Generator is licensed by ${content.license}.

## Questions
GitHub: [${content.username}](https://github.com/${content.username})<br /><br />
Email me: ${content.email}<br /><br />
This README.md was generated by [${content.username}] `;

};

module.exports = generateMarkdown;